window.PLAYLISTS = [
  {
    id: "haryanvi-bangers",
    name: "🔥 Haryanvi Bangers",
    description: "Masoom Sharma, Dhanda Nyoliwala, Khasa Aala Chahar & more",
    tracks: [
      { title: "2 Bhai", artist: "Mohit Ladhotiya", yt: "Cp5clRKpN2g" },
      { title: "4 AADMI", artist: "Sumit Parta", yt: "cx2mC18op-o" },
      { title: "4WD", artist: "Khasa Aala Chahar", yt: "4TbhtL6S1mA" },
      { title: "Badtameez", artist: "Filmy", yt: "OdPjQUVm10s" },
      { title: "Bahu Chaudhariya Ki", artist: "Aman Jaji", yt: "vmELhJZWorM" },
      { title: "Bair Jaat Ka", artist: "CK Nara", yt: "vmO8sapyPh4" },
      { title: "Bair Jaat Ka 2", artist: "CK Nara", yt: "X1ieaUdhnsw" },
      { title: "Bateu Haryane Te", artist: "Masoom Sharma", yt: "zL95KfNnioQ" },
      { title: "Bau Ji", artist: "Mohit Ladhotiya", yt: "d_v9xWiucfU" },
      { title: "Bhai Bhai", artist: "Masoom Sharma", yt: "_G-Cu41dSRw" },
      { title: "BILLA SONIPAT ALA", artist: "My Definition", yt: "3DDUNpmBaDw" },
      { title: "BROTHERHOOD", artist: "Naveen Chaudhary", yt: "u45Up6j6mlU" },
      { title: "Chambal K Dakku", artist: "Masoom Sharma", yt: "LzrPO12JNM0" },
      { title: "Chora Haryane Aala", artist: "Eshan Sunny", yt: "gRwDNOySkiY" },
      { title: "Convoy", artist: "Khasa Aala Chahar", yt: "K_sCoyw6fGg" },
      { title: "Knife Brows", artist: "Dhanda Nyoliwala", yt: "LGz6ibOkeqQ" },
      { title: "Not Guilty", artist: "Dhanda Nyoliwala", yt: "E7ergOnpO1Q" },
      { title: "Russian Bandana", artist: "Dhanda Nyoliwala", yt: "1OAjeECW90E" },
      { title: "Gaadi Paache Gaadi", artist: "Amanraj Gill", yt: "ua6GpI8ugxY" },
      { title: "Gadar", artist: "Sapna Choudhary", yt: "mAHafjRSg8w" },
      { title: "Gold 18 Lakh Ka", artist: "Dholi Honda City", yt: "n9AC-Bsx5H4" },
      { title: "Goli Bhatkan Lagi", artist: "Masoom Sharma", yt: "uNMmr4ID0Ns" },
      { title: "Gundagarh", artist: "Masoom Sharma", yt: "KUF4gE1EBUE" },
      { title: "Gundey Dore Pe", artist: "Sachin Jaat", yt: "zmZ6P8SLLO4" },
      { title: "HARYANVI", artist: "Vikram Malik", yt: "AUNY8KdWIOg" },
      { title: "Heads Up", artist: "Vikram Malik", yt: "n_aGPjmrzgo" },
      { title: "INFAMOUS", artist: "Rupesh Verma", yt: "jWrMbwtIaa0" },
      { title: "Ji Laage Se Babya Mai", artist: "Aman Jaji", yt: "vWOn08GEg7Y" },
      { title: "Kade Na Bhulegi Tu", artist: "Vinu Gaur", yt: "DS6i33S8tj0" },
      { title: "Kamai", artist: "Khasa Aala Chahar", yt: "uf85UxjboMM" },
      { title: "Khaan Ne Daane", artist: "Masoom Sharma", yt: "bGQi95wQVJA" },
      { title: "Khapitar", artist: "Masoom Sharma", yt: "T67f-xjSeCQ" },
      { title: "Khoon Ki Holi", artist: "Masoom Sharma", yt: "aNcguUwzod4" },
      { title: "Long Way from Home", artist: "MC SQUARE", yt: "uU4JRR8vzwU" },
      { title: "LOOK DAGGERS", artist: "Harender Haryanvi", yt: "ExMK-lqHwFc" },
      { title: "Madam Ji", artist: "Masoom Sharma", yt: "LaKNE4u4h34" },
      { title: "MAMA FUFI", artist: "Masoom Sharma", yt: "Euk3LPRKbUg" },
      { title: "Maruti", artist: "Dhanda Nyoliwala", yt: "_ijaEtNzZgw" },
      { title: "JODI NO.1", artist: "Masoom Sharma", yt: "Ww8TmTNXMeA" },
      { title: "NO PARKING", artist: "Masoom Sharma", yt: "X0VOgayBb0I" },
      { title: "Matter", artist: "Sumit Parta", yt: "NJii5FQfhhg" },
      { title: "My Time", artist: "Ndee Kundu", yt: "epz71C4WgMQ" },
      { title: "Not Like You", artist: "Hammy Muzic", yt: "uiFeS5U46kw" },
      { title: "Parna", artist: "Masoom Sharma", yt: "fltoQyC5UF0" },
      { title: "Raat Ke Shikari", artist: "Masoom Sharma", yt: "SBfjg2VDqXw" },
      { title: "RANGKAAT", artist: "Masoom Sharma", yt: "2C_wj-JIbuI" },
      { title: "Rao Sahab Retro", artist: "Vikram Sarkar", yt: "iaiojPxULFI" },
      { title: "RARE", artist: "Rawme Hooda", yt: "XiED-LFz_EE" },
      { title: "Sab Gunday Hai", artist: "Masoom Sharma", yt: "7AApnIrOI14" },
      { title: "Shikari", artist: "Masoom Sharma", yt: "JHbEAayrF5s" },
      { title: "Snap", artist: "Sumit Parta", yt: "SBgtR8r82t0" },
      { title: "Status", artist: "Khasa Aala Chahar", yt: "eKyfRPXEnv8" },
      { title: "Stay Away", artist: "Sinta Bhai", yt: "Lb7vTMJ9v8c" },
      { title: "Sulfa", artist: "Vikas Dhani Aala", yt: "LwnzWAlhRac" },
      { title: "Sabhi Khaas", artist: "Sumit Parta", yt: "PfW4W-EULdU" },
      { title: "Tarraki", artist: "Sumit Parta", yt: "-Ywf65fQDwE" },
      { title: "Tagde Karam", artist: "Sumit Parta", yt: "PSJzUYbpHX0" },
      { title: "TAKEOVER", artist: "Naveen Chaudhary", yt: "ZyAVarn-l6E" },
      { title: "Tere Piche", artist: "Sumit Parta", yt: "PUvktimStlE" },
      { title: "Thaari Bhabhi", artist: "Sumit Parta", yt: "JC6GEfjkyqE" },
      { title: "THAAT", artist: "Babbar", yt: "rd75Vs8pjcQ" },
      { title: "Thekedara Ka Byah", artist: "Masoom Sharma", yt: "zSaddAr8cA0" },
      { title: "Bhartar", artist: "Sumit Parta", yt: "xrcQlkVKQ7A" },
      { title: "SIMPLY US", artist: "Vikram Malik", yt: "L0WvAyzmE50" },
      { title: "Yaari Lekhe", artist: "Khasa Aala Chahar", yt: "FfQ2FwN6omM" },
      { title: "Yaari", artist: "Masoom Sharma", yt: "pEh_2kDfu2w" },
    ]
  },
  {
    id: "haryanvi-love",
    name: "❤️ Haryanvi Love",
    description: "Romantic Haryanvi hits",
    tracks: [
      { title: "Wanna Tell You", artist: "Sach Rana", yt: "28Pdu-BKrEE" },
      { title: "Bairan Banjaare", artist: "Banjare", yt: "oafxkMv4xnc" },
      { title: "Banjaare Suits With Me", artist: "Bulbul", yt: "D37PDb69XJY" },
      { title: "Barsaat Banjaare", artist: "Banjaare", yt: "l59sj6d4jVo" },
      { title: "Call Waiting", artist: "Dhruv Balyaan", yt: "1e1kWrSRdyg" },
      { title: "Haaye Re", artist: "Swati Shukla", yt: "5uEUAAaMcOQ" },
      { title: "HARYANA SIDE", artist: "Dhruv Balyaan", yt: "N19NEUeHnAk" },
      { title: "Her Aura", artist: "Vibhor Singh", yt: "HgfFldDPDqc" },
      { title: "Hum 2 The Kde", artist: "Unknown", yt: "epmX8EipvFU" },
      { title: "KAVITA", artist: "Saaya x Qayaas", yt: "-a_05_Q4u2Y" },
      { title: "KITAB", artist: "Mr Dutt", yt: "oyggBXg6ufM" },
      { title: "Long Way from Home", artist: "MC SQUARE", yt: "uU4JRR8vzwU" },
      { title: "My All", artist: "Sahil Dhull", yt: "XNCJm2nwojY" },
      { title: "Tu Na Samjhe", artist: "Raja", yt: "zBgpikwXLNg" },
      { title: "Aashiq Awara", artist: "Dipsne", yt: "ucJ41Ws3vPU" },
      { title: "Churake", artist: "Vilen x Kanika Kapoor", yt: "QpICROpBFI0" },
      { title: "Kitse", artist: "Nyn Music", yt: "ALZzTBqDvL4" },
      { title: "Malan", artist: "Sonika Singh", yt: "HG4yxlRl7Xg" },
      { title: "Na Jaiyo", artist: "Preet Sirohi", yt: "yxOrU80I4hk" },
      { title: "Tu High Level Ki Chori Se", artist: "Vikash Sheoran", yt: "akMZMPT-VMA" },
    ]
  },
  {
    id: "punjabi",
    name: "🎤 Punjabi",
    description: "AP Dhillon, Karan Aujla, Diljit & Punjabi vibes",
    tracks: [
      { title: "100 Times", artist: "Jordan Sandhu", yt: "yO_fhImQIBU" },
      { title: "By My Side", artist: "AP Dhillon", yt: "sZvn_-S24uw" },
      { title: "Assault", artist: "Manavgeet Gill", yt: "TMcrxHi4R5c" },
      { title: "Boyfriend", artist: "Karan Aujla", yt: "5GCfYLguTIs" },
      { title: "California Love", artist: "Cheema Y", yt: "rSxTumD4kew" },
      { title: "G.O.A.T.", artist: "Diljit Dosanjh", yt: "cl0a3i2wFcc" },
      { title: "Naina", artist: "Diljit Dosanjh", yt: "3u6lLWGjFLY" },
      { title: "Naina (Sukhwinder)", artist: "Sukhwinder Singh", yt: "OzJ-GxokeBc" },
      { title: "Excuses", artist: "AP Dhillon", yt: "vX2cDW8LUWk" },
      { title: "For A Reason", artist: "Karan Aujla", yt: "mJbSH_tucvM" },
      { title: "Jhol", artist: "Maanu", yt: "4O5sFtX4Ddk" },
      { title: "Khat", artist: "Navjot Ahuja", yt: "LUgpPmj6nR8" },
      { title: "Pta Ni", artist: "JERRY", yt: "7IiDFkrSyGU" },
      { title: "Softly", artist: "Karan Aujla", yt: "O8dkCnPnqbM" },
      { title: "Sufna Banke", artist: "Harvi", yt: "YDuVz10Z7xU" },
      { title: "Thinkin", artist: "Shivraj Mundi", yt: "rGwPThWzB_0" },
      { title: "Thinking Of You", artist: "AP Dhillon", yt: "uTZ1JqiQPk4" },
      { title: "Tu Shadya", artist: "Harvi", yt: "UNnpbiDdCOU" },
      { title: "Udaarian", artist: "Satinder Sartaj", yt: "9udS0mpi1L4" },
    ]
  },
  {
    id: "hindi",
    name: "🎵 Hindi",
    description: "Arijit Singh, Vishal Mishra, Anuv Jain & Bollywood hits",
    tracks: [
      { title: "4 Din", artist: "MC SQUARE", yt: "90r1L3wtIiU" },
      { title: "Alag Aasmaan", artist: "Anuv Jain", yt: "koLylOIDocA" },
      { title: "Husn", artist: "Anuv Jain", yt: "gJLVTKhTnog" },
      { title: "Baarishein", artist: "Anuv Jain", yt: "tYqZK7bq5Bs" },
      { title: "Farak Taare", artist: "Farak", yt: "U0EI7XFkkV4" },
      { title: "Haareya", artist: "Arijit Singh", yt: "TyMUY2CDrjc" },
      { title: "Humsafar", artist: "Sachet Tandon", yt: "D9DiMnlpFK8" },
      { title: "Tum Ho Toh", artist: "Vishal Mishra", yt: "rOUuGvJkBrQ" },
      { title: "Paaro", artist: "Aditya Rikhari", yt: "DxsDekHDKXo" },
      { title: "Sahiba", artist: "Aditya Rikhari", yt: "n2dVFdqMYGA" },
      { title: "Sau Tarah Ke", artist: "Pritam", yt: "PIyf0hMc498" },
      { title: "Shikayat", artist: "AUR", yt: "QxddU3sjVRY" },
      { title: "Tainu Khabar Nahi", artist: "Arijit Singh", yt: "6d5SS0gS5bU" },
      { title: "Tumse Behtar", artist: "Various", yt: "MivKhlsMKL0" },
      { title: "Waqt Ki Chal", artist: "Kamal Arora", yt: "J7aglAvLUqU" },
      { title: "Ye Tune Kya Kiya", artist: "Pritam", yt: "w9Qo6p4XsXE" },
    ]
  }
];

window.PLAYLISTS.forEach(function (pl) {
  pl.tracks.forEach(function (t) {
    t.url = 'https://www.youtube.com/embed/' + t.yt + '?enablejsapi=1&autoplay=0';
  });
});

window.QUOTES = [
  "मेहनत आज, सुकून कल. — future me",
  "CGPA is temporary, Code is Forever :)",
  "Attendance 74.9%... Sir 0.1% me debar karoge?",
  "Maggi 2 minute me nahi banti.",
  "Placement hoga tabhi toh Chai me cheeni dalegi.",
  "Sirf 1 semester aur, fir life set hai.",
  "3 AM code compiles on 1st try = Pure Magic ✨",
  "Data Structures padh lo, Baarish toh hoti rahegi 🌧️",
  "Segmentation Fault (core dumped)... Coffee break time ☕",
  "Hostel ki chai & doston ki bakchodi = Life ❤️",
  "Git commit -m 'Fixed bugs, created 10 new ones'",
  "Quiet night, warm tea, heavy rain outside. Life is good.",
];
